NUM_SHIFTS = 3
NUM_CUSTOMERS_BEFORE_X = 20
NUM_CUSTOMERS_BEFORE_Z = 100
MIN_ITEMS_IN_CART = 1
MAX_ITEMS_IN_CART = 10
PAYMENT1 = "Cash"
PAYMENT2 = "Card"
SALES_HEADERS: list[object] = ["Product", "Sales"]
REVENUE_HEADERS: list[object] = ["Payment", "Revenue"]
RECEIPT_HEADERS: list[object] = ["Product", "Units", "Price", "Total"]
DISCOUNT_ON_RECEIPT = 17
PERCENT = 100
STORE_TABLE_NAME = "Store"
X_SALES_TABLE_NAME = "XSales"
X_REVENUE_TABLE_NAME = "XRevenue"
Z_SALES_TABLE_NAME = "ZSales"
Z_REVENUE_TABLE_NAME = "ZRevenue"
DATABASE = "database.db"
TEST_DATABASE = "test_database.db"
